export const CHANGE_LOCATION_GEOCODE = 'CHANGE_LOCATION_GEOCODE';
export const CHANGE_SUGGESTED_ADDRESS = 'CHANGE_SUGGESTED_ADDRESS';
export const CHANGE_LOCATION_INPUT = 'CHANGE_LOCATION_INPUT';
export const RESET_DATA = 'RESET_DATA';
