export const CHANGE_LOCATION_GEOCODE = 'CHANGE_LOCATION_GEOCODE';
export const CHANGE_SUGGESTED_ADDRESS = 'CHANGE_SUGGESTED_ADDRESS';
export const CHANGE_LOCATION_INPUT = 'CHANGE_LOCATION_INPUT';
export const RESET_DATA = 'RESET_DATA';
export const CHANGE_ERROR = 'CHANGE_ERROR';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
